/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agenda;

/**
 *
 * @author aula
 */

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.misc.resources.Messages_pt_BR;

public class frmagenda extends javax.swing.JFrame {

    int linhaselecionada;
    
    /**
     * Creates new form frmagenda
     */
    public frmagenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtnome = new javax.swing.JTextField();
        jtxtemail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxttelefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtcelular = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtdata = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jcmdsexo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jcmdoperadora = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jbtnnovo = new javax.swing.JButton();
        jbtnatualiza = new javax.swing.JButton();
        jbtnexcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agenda/icons8-calendário-48.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(jLabel8)
                .addContainerGap(367, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 740, 80);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados Pessoais"));
        jPanel2.setName(""); // NOI18N

        jLabel1.setText("Nome:");

        jLabel2.setText("E-mail:");

        jLabel3.setText("Telefone");

        jLabel4.setText("Celular");

        jLabel5.setText("Data de Nascimento:");

        jLabel6.setText("Sexo:");

        jcmdsexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Feminino\t", "Masculino", "Outro", " " }));
        jcmdsexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmdsexoActionPerformed(evt);
            }
        });

        jLabel7.setText("Operadora");

        jcmdoperadora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Vivo", "Tim", "Claro", "Oi", "Nextel", " " }));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Data de Nascimento", "E-mail", "Sexo", "Telefone", "Celular", "Operadora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jtxtnome)
                            .addComponent(jtxtemail)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jtxtcelular, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jcmdoperadora, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcmdsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jtxtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcmdsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcmdoperadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 90, 710, 310);

        jbtnnovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agenda/icons8-adicionar-32.png"))); // NOI18N
        jbtnnovo.setText("Novo");
        jbtnnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnnovoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnnovo);
        jbtnnovo.setBounds(120, 430, 120, 41);

        jbtnatualiza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agenda/icons8-seta-para-recolher-32.png"))); // NOI18N
        jbtnatualiza.setText("Atualizar");
        jbtnatualiza.setToolTipText("");
        getContentPane().add(jbtnatualiza);
        jbtnatualiza.setBounds(280, 430, 120, 41);

        jbtnexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agenda/icons8-cancelar-32.png"))); // NOI18N
        jbtnexcluir.setText("Excluir");
        jbtnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnexcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnexcluir);
        jbtnexcluir.setBounds(450, 430, 120, 41);

        setSize(new java.awt.Dimension(745, 529));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jcmdsexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmdsexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmdsexoActionPerformed

    private void jbtnnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnnovoActionPerformed
        // TODO add your handling code here:
        
        //variaveis
        String nome, celular, telefone, operadora, data, email, sexo;
        
        //atribuir os valores das caixas para as variaveis
           nome = jtxtnome.getText();
           celular = jtxtcelular.getText();
           telefone = jtxttelefone.getText();
           email = jtxtemail.getText();
           data = jtxtdata.getText();
           
           operadora = jcmdoperadora.getSelectedItem().toString();
           sexo = jcmdsexo.getSelectedItem().toString();
           
           //adiciona uma nova linha na tabela
           DefaultTableModel modelo = (DefaultTableModel) jTable.getModel();
           modelo.addRow(new Object[]{nome, data, email, sexo, telefone, celular, operadora});
           
           
           //limpar os campos
           jtxtnome.setText("");
           jtxtcelular.setText("");
           jtxtemail.setText("");
           jtxttelefone.setText("");
           jtxtdata.setText("");
           
           jcmdoperadora.setSelectedIndex(0);
           jcmdsexo.setSelectedIndex(0);
    }//GEN-LAST:event_jbtnnovoActionPerformed

    private void jbtnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnexcluirActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel modelo = (DefaultTableModel) jTable.getModel();
        //se foi selecionada alguma linha do jtable
        
        if (jTable.getSelectedRow() >- 0) {
            modelo.removeRow(jTable.getSelectedRow());  
    }//GEN-LAST:event_jbtnexcluirActionPerformed
  else{
            JOptionPane.showMessageDialog(null, "linha não selecionada");
        }
    }   
    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        // TODO add your handling code here:
        
        if (evt.getClickCount() == 2)
        {
            int linha = jTable.getSelectedRow();
            //add os valores nas caixas de texto
            jtxtnome.setText(jTable.getValueAt(linha, 0).toString());
            jtxtdata.setText(jTable.getValueAt(linha, 1).toString());
            jtxtemail.setText(jTable.getValueAt(linha, 2).toString());
            jcmdsexo.setSelectedItem(jTable.getValueAt(linha, 3).toString());
            jtxttelefone.setText(jTable.getValueAt(linha, 4).toString());
            jtxtcelular.setText(jTable.getValueAt(linha, 5).toString());
            jcmdoperadora.setSelectedItem(jTable.getValueAt(linha, 6).toString());
            
            // armazena a linha
            linhaselecionada = linha;
            
        }
        
    }//GEN-LAST:event_jTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmagenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmagenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmagenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmagenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmagenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JButton jbtnatualiza;
    private javax.swing.JButton jbtnexcluir;
    private javax.swing.JButton jbtnnovo;
    private javax.swing.JComboBox<String> jcmdoperadora;
    private javax.swing.JComboBox<String> jcmdsexo;
    private javax.swing.JTextField jtxtcelular;
    private javax.swing.JTextField jtxtdata;
    private javax.swing.JTextField jtxtemail;
    private javax.swing.JTextField jtxtnome;
    private javax.swing.JTextField jtxttelefone;
    // End of variables declaration//GEN-END:variables
}
